### ISSUE TITLE
At the same time and in the same direction, how to determine the leverage multiple used by traders?

### ISSUE THREAD

**Issue by xiaopihaiK** [aoki-h-jp/py-liquidation-map#10]
At the same time and in the same direction, how to determine the leverage multiple used by traders?
Traders with lower margins can only open high leverage, but traders with high margins can open low or high leverage. How do you determine this?

**Comment by aoki-h-jp** [comment]
@xiaopihaiK 

In conclusion, it is not possible to obtain the trader's margin level from the exchange, as this is private information. Therefore, it is not possible to draw a Liquidation Map on the basis of margin.

The code in this repository shows where a trader with a large buy or sell position (determined by various thresholds) would be liquidated if they were trading at 10, 20, 50 or 100 times leverage. For example, if a trader opened a large buy position of 100,000 USDT when BTC/USDT was at 25,000 USDT, 99% = 24,750 USDT, 98% = 24,500 USDT, 95% = 23,750 USDT, 90% = 22,500 USDT a bar chart is drawn representing the liquidation potential of 100,000 USDT. For sell positions, the drawing is done in the opposite way, where the price is 101%, 102%, 105% or 110%. This suggests that a large number of traders are likely to be liquidated at price levels where Depth, which is drawn by accumulating them, is rising rapidly.

**Comment by xiaopihaiK** [comment]
@aoki-h-jp 
I read the code and found that the threshold is determined based on the margin ratio and fee rate. I was wondering if there is a way to determine the average leverage ratio, or to dynamically adjust the liquidation intensity in real time like the liquidation map given by coinglass. tg:https://t.me/Ddvfsdsw I want to have an in-depth communication with you

**Comment by xiaopihaiK** [comment]
@aoki-h-jp 
The rate and margin rate can actually simply determine the liquidation (liquidation) value, but there is no guarantee that traders will not add or reduce their positions before liquidation. This is the most troublesome part. Basically, several screening modes in the code are It is prepared for large investors, but a large number of retail investors are also an uncertain factor in the market. They enter the market quickly but also leave the market quickly, so the position of centralized liquidation cannot be determined, which is very troublesome now.

**Comment by aoki-h-jp** [comment]
@xiaopihaiK 
Thank you for pointing this out. And what you have in mind is an area I struggle with as well.
The following is a summary of the areas you have identified.

- We would like to consider whether it would be possible to calculate something like a dynamic average leverage multiplier in response to market prices and estimate the price range at which the market changes rapidly.
- It may not be possible to know when traders are closing positions.
- The code is good at monitoring the liquidation potential of large investors, but it does not take into account the large number of small traders, and that positions are closed immediately rather than in hours or days

We recognise that all your points are correct and will definitely be taken into account in the future to draw a more accurate Liquidation Map. However, to be honest, I do not currently have any ideas regarding these. All I can say with certainty is that the only information that can be monitored using websockets etc. is that of positions opened by anonymous traders, and this needs to be successfully processed to estimate the above. If you have some ideas and they seem objectively correct, I am ready to reflect them in this code.

**Comment by xiaopihaiK** [comment]
Thank you for your answer!

**Comment by fridary** [comment]
@aoki-h-jp Do you have ideas how to predict liquidations levels in current moment? Here some services that can do. I suppose they use order book data.
https://docs.spreadfighter.com/documentation/microstructural-solutions/sf-liqudations
https://bookmap.com/knowledgebase/docs/Addons-Liquidation-Indicator

**Comment by aoki-h-jp** [comment]
@fridary 
Future plans for this project include not only drawing a Liquidation Map with historical data (HistoricalMapping), but also drawing a real-time Liquidation Map using websockets, etc. ( RealTimeMapping is likely to be the name of the class).
In my personal opinion, I find it very difficult to predict the scale of liquidation at any given time. In most cases, large amounts of liquidation tend to halt abrupt price movements, but I think it is impossible to predict exactly when and where this will stop.
The idea of combining it with the order book may indeed be useful, but in my opinion, the order book only works for price movements within a few seconds and is not very useful for huge price movements that involve liquidation.
I have done some research on the above and I will post a link to my gist on Orderbook Imbalance.
https://gist.github.com/aoki-h-jp/d075341220450e797a4c1047a880d6ee

If you have any ideas, please suggest them and we can incorporate them into our development plan.
