### ISSUE TITLE
EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by pwhong** [aoki-h-jp/py-liquidation-map#11]
What is the most recent data available to plot the liquidation map?

 Based on UTC,
It works fine until 23:59:59 of the previous day, but if I set the input data to today, it doesn't work.

**Comment by aoki-h-jp** [comment]
@pwhong 
Thanks for the report.
The data used in this library is downloaded using my `binance_bulk_downloader` and `bybit_bulk_downloader`.

https://github.com/aoki-h-jp/binance-bulk-downloader
https://github.com/aoki-h-jp/bybit-bulk-downloader

https://github.com/aoki-h-jp/py-liquidation-map/blob/main/liqmap/download.py#L9-L10
https://github.com/aoki-h-jp/py-liquidation-map/blob/main/requirements.txt#L1-L2

In those libraries, the data of the day does not exist because they are downloaded from the following links.

https://data.binance.vision
https://public.bybit.com

Therefore, real-time rendering is currently not supported. In the future, we plan to add a function like RealtimeMapping (however, the timing is undecided, as I am developing this only on my own and am not sure if I can find the time).
Thank you in advance for your cooperation on the above.

**Comment by pwhong** [comment]
Thank you for your response.
I really appreciate your good source code.
I hope you have a great holiday season.
